/**
 * Incident Response Validator
 * Performs field-level verification checks on JSON output generated by Gemini API
 * to prevent runtime rendering crashes in the UI.
 */

import { IncidentAIAnalysis } from './incidentTypes';
import { AIValidationError } from '../shared/aiErrors';

export function validateIncidentAIAnalysis(data: unknown): IncidentAIAnalysis {
  const d = data as Record<string, unknown>;

  if (typeof d.incidentId !== 'string' || d.incidentId.trim().length === 0) {
    throw new AIValidationError('incidentId is missing or invalid', 'incidentId');
  }

  if (typeof d.classification !== 'string' || d.classification.trim().length === 0) {
    throw new AIValidationError('classification is missing or empty', 'classification');
  }

  const urgency = d.urgencyLevel as string;
  if (!['LOW', 'MODERATE', 'HIGH', 'CRITICAL'].includes(urgency)) {
    throw new AIValidationError(`urgencyLevel is invalid: ${urgency}`, 'urgencyLevel');
  }

  if (!Array.isArray(d.suggestedDispatches)) {
    throw new AIValidationError('suggestedDispatches must be an array', 'suggestedDispatches');
  }

  if (typeof d.estimatedResolutionMinutes !== 'number' || d.estimatedResolutionMinutes < 0) {
    throw new AIValidationError('estimatedResolutionMinutes must be a positive number', 'estimatedResolutionMinutes');
  }

  if (typeof d.confidence !== 'number' || d.confidence < 0 || d.confidence > 1) {
    throw new AIValidationError('confidence must be between 0 and 1', 'confidence');
  }

  const confCategory = d.confidenceCategory as string;
  if (!['High', 'Medium', 'Low'].includes(confCategory)) {
    throw new AIValidationError(`confidenceCategory is invalid: ${confCategory}`, 'confidenceCategory');
  }

  if (typeof d.reasoning !== 'string' || d.reasoning.trim().length === 0) {
    throw new AIValidationError('reasoning is missing or empty', 'reasoning');
  }

  if (!Array.isArray(d.mitigationSuggestions)) {
    throw new AIValidationError('mitigationSuggestions must be an array', 'mitigationSuggestions');
  }

  if (typeof d.generatedAt !== 'string') {
    throw new AIValidationError('generatedAt is missing or invalid', 'generatedAt');
  }

  return data as IncidentAIAnalysis;
}
